# Generated by Django 5.2.5 on 2025-08-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customdocument",
            name="source",
        ),
    ]
