# Generated by Django 5.2.5 on 2025-08-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customimage",
            name="copyright",
        ),
        migrations.AlterField(
            model_name="customrendition",
            name="file",
            field=models.ImageField(
                height_field="height",
                upload_to="images/renditions/",
                width_field="width",
            ),
        ),
    ]
